// GENERATED by apps/web/art-src/gen-arcade-audio.py — do not edit by hand.
//
// Every clip the arcade can play, by name (public/assets/arcade/audio).
// Voices are per fighter, per line kind, with one or more takes each.

export const AUDIO = {
  "sfx": {
    "hit_light": "/assets/arcade/audio/sfx/hit_light-v2.mp3",
    "hit_heavy": "/assets/arcade/audio/sfx/hit_heavy-v2.mp3",
    "block": "/assets/arcade/audio/sfx/block-v2.mp3",
    "whiff": "/assets/arcade/audio/sfx/whiff-v2.mp3",
    "jump": "/assets/arcade/audio/sfx/jump-v2.mp3",
    "land": "/assets/arcade/audio/sfx/land-v2.mp3",
    "special": "/assets/arcade/audio/sfx/special.mp3",
    "projectile_hit": "/assets/arcade/audio/sfx/projectile_hit.mp3",
    "ko": "/assets/arcade/audio/sfx/ko.mp3",
    "round_bell": "/assets/arcade/audio/sfx/round_bell.mp3",
    "timeout_buzzer": "/assets/arcade/audio/sfx/timeout_buzzer.mp3",
    "select_move": "/assets/arcade/audio/sfx/select_move.mp3",
    "select_confirm": "/assets/arcade/audio/sfx/select_confirm.mp3",
    "versus_sting": "/assets/arcade/audio/sfx/versus_sting.mp3",
    "round_win": "/assets/arcade/audio/sfx/round_win.mp3",
    "pause": "/assets/arcade/audio/sfx/pause.mp3",
    "unlock_jingle": "/assets/arcade/audio/sfx/unlock_jingle.mp3",
    "cabinet_thud": "/assets/arcade/audio/sfx/cabinet_thud.mp3",
    "horn_attack": "/assets/arcade/audio/sfx/horn_attack-v2.mp3",
    "ice_slam": "/assets/arcade/audio/sfx/ice_slam-v2.mp3",
    "math_circle": "/assets/arcade/audio/sfx/math_circle-v2.mp3",
    "water_orb": "/assets/arcade/audio/sfx/water_orb-v2.mp3",
    "prime_laser": "/assets/arcade/audio/sfx/prime_laser-v2.mp3",
    "redline_vision": "/assets/arcade/audio/sfx/redline_vision-v3.mp3",
    "laser_rain": "/assets/arcade/audio/sfx/laser_rain-v2.mp3",
    "breaking_news_charge": "/assets/arcade/audio/sfx/breaking_news_charge-v3.mp3",
    "breaking_news_release": "/assets/arcade/audio/sfx/breaking_news_release-v3.mp3",
    "breaking_news_impact": "/assets/arcade/audio/sfx/breaking_news_impact-v3.mp3"
  },
  "music": {
    "title": {
      "url": "/assets/arcade/audio/music/title.mp3",
      "loop": true
    },
    "select": {
      "url": "/assets/arcade/audio/music/select.mp3",
      "loop": true
    },
    "fight": {
      "url": "/assets/arcade/audio/music/fight.mp3",
      "loop": true
    },
    "victory": {
      "url": "/assets/arcade/audio/music/victory.mp3",
      "loop": false
    },
    "gameover": {
      "url": "/assets/arcade/audio/music/gameover.mp3",
      "loop": false
    }
  },
  "voices": {
    "bull": {
      "specialUp": [],
      "dash": [],
      "ice": [],
      "circle": [],
      "orb": [],
      "breakingNews": [],
      "attack": [
        "/assets/arcade/audio/voice/bull/attack_1-v2.mp3",
        "/assets/arcade/audio/voice/bull/attack_2-v2.mp3"
      ],
      "special": [
        "/assets/arcade/audio/voice/bull/special_1-v2.mp3"
      ],
      "outOfEnergy": [
        "/assets/arcade/audio/voice/bull/outOfEnergy_1-v2.mp3"
      ],
      "hurt": [
        "/assets/arcade/audio/voice/bull/hurt_1-v2.mp3",
        "/assets/arcade/audio/voice/bull/hurt_2-v2.mp3"
      ],
      "ko": [
        "/assets/arcade/audio/voice/bull/ko_1-v2.mp3"
      ],
      "intro": [
        "/assets/arcade/audio/voice/bull/intro_1-v2.mp3"
      ],
      "win": [
        "/assets/arcade/audio/voice/bull/win_1-v2.mp3"
      ]
    },
    "bear": {
      "specialUp": [],
      "dash": [],
      "ice": [],
      "circle": [],
      "orb": [],
      "breakingNews": [],
      "attack": [
        "/assets/arcade/audio/voice/bear/attack_1-v2.mp3",
        "/assets/arcade/audio/voice/bear/attack_2-v2.mp3"
      ],
      "special": [
        "/assets/arcade/audio/voice/bear/special_1-v2.mp3"
      ],
      "outOfEnergy": [
        "/assets/arcade/audio/voice/bear/outOfEnergy_1-v2.mp3"
      ],
      "hurt": [
        "/assets/arcade/audio/voice/bear/hurt_1-v2.mp3",
        "/assets/arcade/audio/voice/bear/hurt_2-v2.mp3"
      ],
      "ko": [
        "/assets/arcade/audio/voice/bear/ko_1-v2.mp3"
      ],
      "intro": [
        "/assets/arcade/audio/voice/bear/intro_1-v2.mp3"
      ],
      "win": [
        "/assets/arcade/audio/voice/bear/win_1-v2.mp3"
      ]
    },
    "quant": {
      "specialUp": [],
      "dash": [],
      "ice": [],
      "circle": [],
      "orb": [],
      "breakingNews": [],
      "attack": [
        "/assets/arcade/audio/voice/quant/attack_1-v2.mp3",
        "/assets/arcade/audio/voice/quant/attack_2-v2.mp3"
      ],
      "special": [
        "/assets/arcade/audio/voice/quant/special_1-v2.mp3"
      ],
      "outOfEnergy": [
        "/assets/arcade/audio/voice/quant/outOfEnergy_1-v2.mp3"
      ],
      "hurt": [
        "/assets/arcade/audio/voice/quant/hurt_1-v2.mp3",
        "/assets/arcade/audio/voice/quant/hurt_2-v2.mp3"
      ],
      "ko": [
        "/assets/arcade/audio/voice/quant/ko_1-v2.mp3"
      ],
      "intro": [
        "/assets/arcade/audio/voice/quant/intro_1-v2.mp3"
      ],
      "win": [
        "/assets/arcade/audio/voice/quant/win_1-v2.mp3"
      ]
    },
    "whale": {
      "specialUp": [],
      "dash": [],
      "ice": [],
      "circle": [],
      "orb": [],
      "breakingNews": [],
      "attack": [
        "/assets/arcade/audio/voice/whale/attack_1-v2.mp3",
        "/assets/arcade/audio/voice/whale/attack_2-v2.mp3"
      ],
      "special": [
        "/assets/arcade/audio/voice/whale/special_1-v2.mp3"
      ],
      "outOfEnergy": [
        "/assets/arcade/audio/voice/whale/outOfEnergy_1-v2.mp3"
      ],
      "hurt": [
        "/assets/arcade/audio/voice/whale/hurt_1-v2.mp3",
        "/assets/arcade/audio/voice/whale/hurt_2-v2.mp3"
      ],
      "ko": [
        "/assets/arcade/audio/voice/whale/ko_1-v2.mp3"
      ],
      "intro": [
        "/assets/arcade/audio/voice/whale/intro_1-v2.mp3"
      ],
      "win": [
        "/assets/arcade/audio/voice/whale/win_1-v2.mp3"
      ]
    },
    "primey": {
      "specialUp": [],
      "dash": [],
      "ice": [],
      "circle": [],
      "orb": [],
      "breakingNews": [],
      "attack": [
        "/assets/arcade/audio/voice/primey/attack_1-v2.mp3",
        "/assets/arcade/audio/voice/primey/attack_2-v2.mp3"
      ],
      "special": [
        "/assets/arcade/audio/voice/primey/special_1-v2.mp3"
      ],
      "outOfEnergy": [
        "/assets/arcade/audio/voice/primey/outOfEnergy_1-v2.mp3"
      ],
      "hurt": [
        "/assets/arcade/audio/voice/primey/hurt_1-v2.mp3",
        "/assets/arcade/audio/voice/primey/hurt_2-v2.mp3"
      ],
      "ko": [
        "/assets/arcade/audio/voice/primey/ko_1-v2.mp3"
      ],
      "intro": [
        "/assets/arcade/audio/voice/primey/intro_1-v2.mp3"
      ],
      "win": [
        "/assets/arcade/audio/voice/primey/win_1-v2.mp3"
      ]
    },
    "bernard": {
      "specialUp": [
        "/assets/arcade/audio/voice/bernard/specialUp_1-v3.mp3"
      ],
      "dash": [
        "/assets/arcade/audio/voice/bernard/dash_1-v3.mp3"
      ],
      "ice": [
        "/assets/arcade/audio/voice/bernard/ice_1-v3.mp3"
      ],
      "circle": [
        "/assets/arcade/audio/voice/bernard/circle_1-v3.mp3"
      ],
      "orb": [
        "/assets/arcade/audio/voice/bernard/orb_1-v3.mp3"
      ],
      "breakingNews": [
        "/assets/arcade/audio/voice/bernard/breakingNews_1-v3.mp3"
      ],
      "attack": [
        "/assets/arcade/audio/voice/bernard/attack_1-v3.mp3",
        "/assets/arcade/audio/voice/bernard/attack_2-v3.mp3"
      ],
      "special": [
        "/assets/arcade/audio/voice/bernard/special_1-v3.mp3"
      ],
      "outOfEnergy": [
        "/assets/arcade/audio/voice/bernard/outOfEnergy_1-v3.mp3"
      ],
      "hurt": [
        "/assets/arcade/audio/voice/bernard/hurt_1-v3.mp3",
        "/assets/arcade/audio/voice/bernard/hurt_2-v3.mp3"
      ],
      "ko": [
        "/assets/arcade/audio/voice/bernard/ko_1-v3.mp3"
      ],
      "intro": [
        "/assets/arcade/audio/voice/bernard/intro_1-v3.mp3"
      ],
      "win": [
        "/assets/arcade/audio/voice/bernard/win_1-v3.mp3"
      ]
    }
  },
  "announcer": {
    "round1": "/assets/arcade/audio/announcer/round1-v3.mp3",
    "round2": "/assets/arcade/audio/announcer/round2-v3.mp3",
    "final_round": "/assets/arcade/audio/announcer/final_round-v3.mp3",
    "fight": "/assets/arcade/audio/announcer/fight-v3.mp3",
    "ko": "/assets/arcade/audio/announcer/ko-v3.mp3",
    "time_over": "/assets/arcade/audio/announcer/time_over-v3.mp3",
    "you_win": "/assets/arcade/audio/announcer/you_win-v3.mp3",
    "you_lose": "/assets/arcade/audio/announcer/you_lose-v3.mp3",
    "draw": "/assets/arcade/audio/announcer/draw-v3.mp3",
    "player_one_wins": "/assets/arcade/audio/announcer/player_one_wins-v3.mp3",
    "player_two_wins": "/assets/arcade/audio/announcer/player_two_wins-v3.mp3",
    "perfect": "/assets/arcade/audio/announcer/perfect-v3.mp3"
  }
} as const

export type SfxName = keyof typeof AUDIO.sfx
export type MusicName = keyof typeof AUDIO.music
export type AnnouncerName = keyof typeof AUDIO.announcer
export type VoiceLine = keyof (typeof AUDIO.voices)["bull"]
