// GENERATED by apps/web/art-src/pack-stage.py — do not edit by hand.
//
// The fighting stage's parallax layers (public/assets/arcade/stage-*). Every
// rect is in MASTER pixels on a shared 1672×941 canvas; the renderer scales
// that canvas to its view and slides each layer by `factor` × the camera
// offset. The floor is the play plane (factor 0); the fighters' feet sit on
// `footBaseline`.

export interface StageLayer { url: string; x: number; y: number; w: number; h: number; factor: number }

export const STAGE = {
  "width": 1672,
  "height": 941,
  "footBaseline": 760,
  "layers": {
    "far": {
      "url": "/assets/arcade/stage-far-v10.jpg",
      "x": 0,
      "y": 0,
      "w": 1672,
      "h": 941,
      "factor": 0.06
    },
    "tables": {
      "url": "/assets/arcade/stage-tables.png",
      "x": 133,
      "y": 387,
      "w": 1405,
      "h": 139,
      "factor": 0.16
    },
    "floor": {
      "url": "/assets/arcade/stage-floor.png",
      "x": 0,
      "y": 521,
      "w": 1672,
      "h": 420,
      "factor": 0
    }
  }
} as const satisfies { width: number; height: number; footBaseline: number; layers: Record<"far" | "tables" | "floor", StageLayer> }
