// GENERATED by pack-ui.py / scripts/pack-polar-bear.ts.
export const UI_ART = {
  "screens": {
    "title": {
      "url": "/assets/arcade/ui-title-v6.jpg",
      "w": 1672,
      "h": 941
    },
    "select": {
      "url": "/assets/arcade/ui-select.jpg",
      "w": 1672,
      "h": 941
    }
  },
  "portraits": {
    "bull": "/assets/arcade/ui-portrait-bull-v4.png",
    "bear": "/assets/arcade/ui-portrait-bear-v6.png",
    "quant": "/assets/arcade/ui-portrait-quant-v4.png",
    "whale": "/assets/arcade/ui-portrait-whale-v4.png",
    "bernard": "/assets/arcade/ui-portrait-bernard.jpg",
    "primey": "/assets/arcade/ui-portrait-primey.jpg"
  }
} as const
