// GENERATED by art-src/pack-duel-art.py — do not edit.
import type { DeckId } from "./cards"

export const CARD_ART: Record<string, string> = {
  "bears/bankruptcy": "/assets/duel/bears-bankruptcy.webp",
  "bears/bear-raid": "/assets/duel/bears-bear-raid.webp",
  "bears/bearish-analyst": "/assets/duel/bears-bearish-analyst.webp",
  "bears/grizzly": "/assets/duel/bears-grizzly.webp",
  "bears/liquidation": "/assets/duel/bears-liquidation.webp",
  "bears/market-crash": "/assets/duel/bears-market-crash.webp",
  "bears/short-seller": "/assets/duel/bears-short-seller.webp",
  "bears/vulture-fund": "/assets/duel/bears-vulture-fund.webp",
  "bulls/day-trader": "/assets/duel/bulls-day-trader.webp",
  "bulls/flash-crash": "/assets/duel/bulls-flash-crash.webp",
  "bulls/leveraged-long": "/assets/duel/bulls-leveraged-long.webp",
  "bulls/meme-stock": "/assets/duel/bulls-meme-stock.webp",
  "bulls/momentum-chaser": "/assets/duel/bulls-momentum-chaser.webp",
  "bulls/pump-rally": "/assets/duel/bulls-pump-rally.webp",
  "bulls/raging-bull": "/assets/duel/bulls-raging-bull.webp",
  "bulls/short-squeeze": "/assets/duel/bulls-short-squeeze.webp",
  "quants/algo-bot": "/assets/duel/quants-algo-bot.webp",
  "quants/alpha-signal": "/assets/duel/quants-alpha-signal.webp",
  "quants/arbitrage": "/assets/duel/quants-arbitrage.webp",
  "quants/backtest": "/assets/duel/quants-backtest.webp",
  "quants/black-box": "/assets/duel/quants-black-box.webp",
  "quants/hft-cluster": "/assets/duel/quants-hft-cluster.webp",
  "quants/intern-analyst": "/assets/duel/quants-intern-analyst.webp",
  "quants/quant-fund": "/assets/duel/quants-quant-fund.webp",
  "whales/blue-chip": "/assets/duel/whales-blue-chip.webp",
  "whales/buyback": "/assets/duel/whales-buyback.webp",
  "whales/compound-interest": "/assets/duel/whales-compound-interest.webp",
  "whales/dividend": "/assets/duel/whales-dividend.webp",
  "whales/humpback": "/assets/duel/whales-humpback.webp",
  "whales/index-fund": "/assets/duel/whales-index-fund.webp",
  "whales/sardine-school": "/assets/duel/whales-sardine-school.webp",
  "whales/sovereign-fund": "/assets/duel/whales-sovereign-fund.webp"
}

export const DECK_ART: Record<DeckId, string> = {
  "bears": "/assets/duel/bears-emblem.webp",
  "bulls": "/assets/duel/bulls-emblem.webp",
  "quants": "/assets/duel/quants-emblem.webp",
  "whales": "/assets/duel/whales-emblem.webp"
}

/** Each faction's playmat; the board uses the house's. */
export const PLAYMAT: Record<DeckId, string> = {
  "bears": "/assets/duel/mat-bears.webp",
  "bulls": "/assets/duel/mat-bulls.webp",
  "quants": "/assets/duel/mat-quants.webp",
  "whales": "/assets/duel/mat-whales.webp"
}

export const CARD_BACK = "/assets/duel/card-back.webp"
export const MANA_CRYSTAL = "/assets/duel/mana-crystal.webp"
