// GENERATED by apps/web/art-src/gen-duel-audio.py — do not edit by hand.
//
// Every clip the duel can play, by name (public/assets/duel/audio).

export const DUEL_AUDIO = {
  "sfx": {
    "confirm": "/assets/duel/audio/sfx/confirm.mp3",
    "card": "/assets/duel/audio/sfx/card.mp3",
    "draw": "/assets/duel/audio/sfx/draw.mp3",
    "summon": "/assets/duel/audio/sfx/summon.mp3",
    "attack": "/assets/duel/audio/sfx/attack.mp3",
    "hit": "/assets/duel/audio/sfx/hit.mp3",
    "spell": "/assets/duel/audio/sfx/spell.mp3",
    "burn": "/assets/duel/audio/sfx/burn.mp3",
    "destroy": "/assets/duel/audio/sfx/destroy.mp3",
    "heal": "/assets/duel/audio/sfx/heal.mp3",
    "pump": "/assets/duel/audio/sfx/pump.mp3",
    "bounce": "/assets/duel/audio/sfx/bounce.mp3",
    "drain": "/assets/duel/audio/sfx/drain.mp3",
    "turn": "/assets/duel/audio/sfx/turn.mp3"
  },
  "music": {
    "table": {
      "url": "/assets/duel/audio/music/table.mp3",
      "loop": true
    },
    "win": {
      "url": "/assets/duel/audio/music/win.mp3",
      "loop": false
    },
    "lose": {
      "url": "/assets/duel/audio/music/lose.mp3",
      "loop": false
    }
  }
} as const

export type DuelSfxName = keyof typeof DUEL_AUDIO.sfx
export type DuelMusicName = keyof typeof DUEL_AUDIO.music
